In [24]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 

warnings.filterwarnings('ignore')

In [25]:
df = pd.read_csv('movies_metadata.csv')

In [26]:
#  NLP workflow 

#  Find the useful cols for model creation

In [27]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 38.8+ MB

In [29]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [30]:
df['production_companies']

0           [{'name': 'Pixar Animation Studios', 'id': 3}]
1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3        [{'name': 'Twentieth Century Fox Film Corporat...
4        [{'name': 'Sandollar Productions', 'id': 5842}...
                               ...
45461                                                   []
45462               [{'name': 'Sine Olivia', 'id': 19653}]
45463    [{'name': 'American World Pictures', 'id': 6165}]
45464                 [{'name': 'Yermoliev', 'id': 88753}]
45465                                                   []
Name: production_companies, Length: 45466, dtype: str

In [31]:
df.duplicated().sum()

df = df.drop_duplicates().reset_index(drop=True)

In [32]:
required_cols = ['title','genres', 'overview','popularity', 'tagline','vote_average']

df_new = df[required_cols]

In [33]:
import ast

x = "[1, 2, 3, 4]"

# result = 

for i in ast.literal_eval(x):
    print(i)

# print( result)

1
2
3
4

In [34]:
df_new.isnull().sum()

df_new['overview'] = df_new['overview'].fillna('')

In [35]:
#  extract genres from the text dict 
df_new['genres'] = df_new['genres'].apply( lambda x: " ".join( [  i['name'] for i in ast.literal_eval(x)   ] ))

In [36]:
df_new

,title,genres,overview,popularity,tagline,vote_average
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,NaN,7.7
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,6.9
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,6.5
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,6.1
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,5.7
...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,0.072051,Rising and falling between a man and woman,4.0
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,0.178241,NaN,9.0
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",0.903007,A deadly game of wits.,3.8
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",0.003503,NaN,0.0
45452,Queerama,,50 years after decriminalisation of homosexual...,0.163015,NaN,0.0

In [37]:
df_new['tagline']= df_new['tagline'].fillna("")

In [38]:
df_new.isnull().sum()

title           6
genres          0
overview        0
popularity      5
tagline         0
vote_average    6
dtype: int64

In [39]:
df_new = df_new.dropna(subset=['title'])

In [40]:
df_new.isnull().sum()

title           0
genres          0
overview        0
popularity      0
tagline         0
vote_average    0
dtype: int64

In [41]:
df_new['tags'] = df_new['overview']+ " "+ df_new['genres']+" " + df_new['tagline']

In [42]:
df_new.head()

,title,genres,overview,popularity,tagline,vote_average,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,,7.7,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,6.9,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,6.5,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,6.1,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,5.7,Just when George Banks has recovered from his ...

In [43]:
#  Convert the text into  lower case 
#  Remove special characters like punctuations
#  remove stop words
#  lemetization ( converting the words to it's nearest dict meaning )
#  tokenize the words ( splits the text into words )
#  vectorizing ( converting the tokens into numeric format )

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [44]:
stop_words =  set( stopwords.words('english'))
lemetizer = WordNetLemmatizer()

In [45]:
def preprocess_text(text):
    text = str(text.lower())
    text =  re.sub(r'[^\w\s]', "", text)
    words = text.split()
    words = [ word for word in words if word not in stop_words ]
    words = [ lemetizer.lemmatize(word)  for word in words ]
    return " ".join(words)

In [46]:
df_new['tags']= df_new['tags'].apply( preprocess_text)

In [47]:
#  Since we'll be using the cosine similarity algorithm we are going to need the indices so, we are creating a indicesabs

indices = pd.Series(df_new.index , index= df_new['title'])
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45448
Century of Birthing            45449
Betrayal                       45450
Satan Triumphant               45451
Queerama                       45452
Length: 45447, dtype: int64

In [48]:
df_new.head()

,title,genres,overview,popularity,tagline,vote_average,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,,7.7,led woody andys toy live happily room andys bi...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,6.9,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,6.5,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,6.1,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,5.7,george bank recovered daughter wedding receive...

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

#  Here we are restricting the dictinary size to 50K so that the size stay same irrespective of word size
tfidf = TfidfVectorizer( max_features=50000, ngram_range= (1, 2,), stop_words= 'english')

tfidf_matrix = tfidf.fit_transform(df_new['tags'])

In [50]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1555624 stored elements and shape (45447, 50000)>

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
def recomend_movie( title , n=10):
    if title not in indices:
        return['Movie not found']
    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix ).flatten()
    similar_index = sim_score.argsort()[::-1][1:n+1]
    return df_new['title'].iloc[similar_index]

In [53]:
recomend_movie( 'Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24514                 Small Fry
28974           Superstar Goofy
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1931                  Condorman
1071      Rebel Without a Cause
485                      Malice
Name: title, dtype: str

#  _____________Till Here model creation is done _________________

In [54]:
#  let convert this model into a pickle file to use it in a real project

In [55]:
# import pickle

# pickle.dump(df_new, open('df_new.pkl', 'wb'))
# pickle.dump(tfidf , open('tfidf.pkl', 'wb'))
# pickle.dump(indices, open('indices.pkl', 'wb'))
# pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb') )